### ISSUE TITLE
Add a "de-latch" command

### ISSUE THREAD

**Issue by HerrahStrings** [xSke/PluralKit#163]
Similar to `pk;switch out`, makes pluralkit "Forget" what the last proxy was, making further messages not be proxied while not disabling the latch mode.
Latch is the "quietest" autoproxy mode, so making the operation similar is preferable - I see the two options as: 
`pk;unlatch` (pluralkit then deletes message)
Or
```
pk;system unlatchproxy ¬text
¬message
```

Useful for a system that prefers to present a certain member using their default discord profile

**Comment by neonpixii** [comment]
I would love to see this, especially if, as well as a `pk;` command it could be also implemented as a "null" proxy tag, i.e. a text proxy tag that just explicitly returns the users to a non-proxied state.

this would be helpful for both quickness of typing (you could delatch with just a single character at the beginning of your message if you wanetd to, rather than having to type `pk; delatch`), and it allows the user to not have to switch to the server's command spam channel or clog up a channel's chat logs with pk commands

**Comment by Fidgetcetera** [comment]
yeah, extremely would like to have the "null" proxy tag like this - if we did, we'd probably exclusively use latch mode

**Comment by HerrahStrings** [comment]
going to note that this is *almost* achieved using `pk;member x autoproxy off` in latch mode, where the first message sent will be proxied by the user, and subsequent messages will be displayed without proxy

**Comment by UsernameNotAvalible** [comment]
Putting \\\\ in front of a message will break you out of a latch

**Comment by spiralw** [comment]
^^
