### ISSUE TITLE
Carl-bot log cleaning no longer works.

### ISSUE THREAD

**Issue by zobos** [xSke/PluralKit#195]
Now, all Carl-bot "deleted message" logs immediately get deleted by PluralKit, even if the message isn't from a proxy host.

Video example:
https://cdn.discordapp.com/attachments/667795132971614229/730412860793946173/Screen_Recording_2020-07-08_at_14.16.48.mov

**Comment by ent3r** [comment]
Same thing happens in my server. Quite annoying since I can't see any deleted messages the last couple days

**Comment by acw0** [comment]
This is apparently due to the database returning a message ID for *all* fuzzy message queries (where the logger bot does not provide the deleted message ID, and pluralkit has to guess).

I've been meaning to look into this but i've been away from home all day, hopefully i'll get to it tonight or tomorrow morning~

**Comment by ent3r** [comment]
the quicker the better. I've had to disable logclean in my server, since *most* logs are getting deleted

**Comment by zobos** [comment]
I’m not too rushed but this would be very helpful to be fixed

**Comment by xSke** [comment]
Y'all are not gonna like this diff.

**Comment by zobos** [comment]
> Y'all are not gonna like this diff.

? I’m confused

**Comment by ent3r** [comment]
Oh, this will be fun... Let's see what's changed

**Comment by zobos** [comment]
> wow. small error with large bugs

Easy to get wrong 🤷‍♀️
