### ISSUE TITLE
Add feature to set reminders to be shown when system members switch in

### ISSUE THREAD

**Issue by liminalitythree** [xSke/PluralKit#236]
SystemTime has a feature where you can set a reminder for an individual member that will be shown to them when they switch in.

The commands could be something like:

`pk;m <member> remind <reminder text>` to set a reminder
possibly `pk;m <member> remind` to view the current reminder?

If a reminder is already set for the member the `remind` command would add to it.

**Comment by xSke** [comment]
What's the use case for this? I'm not sure why this is a feature the bot needs.

**Comment by dev-kittens** [comment]
I think this is a valid feature request. Many systems, including us, would appreciate having reminders or notes sent to each member when they switch in.
While it is true that a different bot could do this better, there's not really a good way for something outside of PluralKit to know when a switch is logged (or when a message is sent - some people don't use switch commands). 
Also, the integration with PluralKit itself would probably make people more comfortable than having it in another bot.

**Comment by liminalitythree** [comment]
It's useful for systems that experience amnesia between members to communicate between themselves easier. Or just who want to remind/show things to certain members i guess.

I know some systems that use SystemTime just for this feature (even though it goes down often)

and @dev-kittens sending the reminder when the a message is sent is a really good idea! I didn't think of that

**Comment by sysfits** [comment]
we personally would find it super useful cause we only use st for the reminders and nothing else and it's kinda annoying having to like disable it on servers just cause we use reminders

**Comment by Shylke** [comment]
Would definitely use this feature if it gets implemented. Let's say I want to leave a message for Member B if they switch in, most reminder bots allow you to specify to remind in x time, like 10 hours for example, but the thing is I don't know _if_ Member B will switch in 10 hours, or _when_ at all. So having a reminder feature that relies on switches/proxies instead of relative time would be super helpful.

**Comment by spiralw** [comment]
Oops, forgot to comment on this issue!

This feature would fit best as an *extension* to PluralKit, rather than a core feature. APIv2 (launching soon) will have a "webhooks" feature, to send events such as "member switched in" or "sent message" to a custom HTTP server, so a different bot would be able to implement this feature through that.

**Comment by Qyriad** [comment]
> This feature would fit best as an _extension_ to PluralKit, rather than a core feature. APIv2 (launching soon) will have a "webhooks" feature, to send events such as "member switched in" or "sent message" to a custom HTTP server

For future searchers, this now-implemented feature is documented here: https://pluralkit.me/api/dispatch/
