### ISSUE TITLE
You can access member cards from accounts not in the server

### ISSUE THREAD

**Issue by anarchyrain** [xSke/PluralKit#280]
I have a system member who happens to have a five-letter display name (Seven), but recently found he was unable to switch in using that name. When I ran pk;m seven, I got a profile card for someone not in the server and who I don't believe I share any servers with (though I am not completely sure).

Expected behaviour: I'd see Seven's profile information, as I had any time before that.

What actually happened: I was given a member card for another system's member.

Renaming Seven's profile seems to have re-prioritized his profile, but it woulr make more sense for member commands to prioritize one's system displaynames over another system's ID, especially since their info was completely unintentionally accessed.

**Comment by xSke** [comment]
Currently, the lookup order for members is:
- Member name
- 5-letter member ID
- Member display name

This issue is, in theory, intended behavior. You can look up any member using the 5-letter ID and you'll see that member's public information (this is one reason why privacy settings exist). However, I do realize that it's not the most intuitive, and there are potential issues with sharing unwanted information.

I don't think we'll reprioritize the lookup order, but member ID "collisions" are starting to happen frequently enough that the system may need to fundamentally change. One potential solution could be requiring a symbol in order to look up by ID (eg. `pk;member #abcde` or `pk;member @abcde`)?

**Comment by anarchyrain** [comment]
Thanks for the quick response!

That order definitely makes sense. And honestly, my first instincts for a fix that didn't *also* potentially break administrative/intentional system lookups was to add an optional parameter to look up in a specific system (either by system ID or account tag/ID), but literally anything to filter 
between "my system" and "universally/another system" could help fix this (with the caveat of "a lot of users potentially have to get used to a new-ish feature" if too much is changed.)

Most of my confusion/concern with this is that this info seems to be accessible to people not sharing a server with the user/who have potentially no indication that someone has accessed their info, meaning that if I were malicious, I could simply take the info from their member card, run a lookup on their system, and find/leak significant amounts of information that they maybe didn't want/know was as public as it was. (I know the privacy settings exist for a reason, but frankly, before this I had no reason to think someone I don't know could access my system info without at least knowing my system ID.)

Thank you again for the quick response!

**Comment by xSke** [comment]
It's a design decision to not really make a distinction between "person with mutual servers" and not, partially because I don't think it's a particularly useful line to draw (there are a lot of very big servers and just sharing one of those generally doesn't imply a relationship where privacy restrictions should be loosened up), and partially for technical reasons (we'd have to store several million users' entire server lists).

The intent of the design is that everything you put in your system/member profiles are public until stated otherwise, but I do know that that's not always what users expect in practice. It's a hard problem to solve and I know the current solution is far from optimal; just not a whole lot of good options.

**Comment by spiralw** [comment]
The member lookup order has now been changed to `Member name` -> `Member display name` -> `Member ID`, so it's harder for someone to accidentally get a member from a different system if their name is someone else's ID.

There may be "trusted servers" in the future where certain information is public when queried in the server but private globally, but it's not feasible for PluralKit to restrict access based on shared servers (and the other stuff @xSke mentioned, etc)
