### ISSUE TITLE
Quick-Edit proxied member using pk;edit

### ISSUE THREAD

**Issue by sisby-folk** [xSke/PluralKit#331]
Right now, when a recently sent message without a proxy tag is edited to include a proxy tag, the bot will proxy that message

`pk;edit` now allows users to edit recently sent proxied messages, so it would be great to allow users to change the proxied member on recent messages using `pk;edit` and adding the proxy tag - for example, when an unexpected member is autoproxied using `latch`

This should only be able to be performed on recently sent messages, and can be set to occur only once per message (to prevent spam)

Usage example (unexpected latch):
```
User: test
[Message is deleted by pluralkit] 
Member1: test
User: pk;edit proxy2testtest
[Both messages are deleted by pluralkit] 
Member2: testtest
```

**Comment by toranine09** [comment]
Not advisable. Discord doesn’t allow you to edit the name/picture on a message sent by a webhook, and reposting the message with the correct proxy may cause the conversation to become disordered if users reply to the message before the edit is made.

**Comment by HerrahStrings** [comment]
As referenced, this is already possible with unproxied messages (within a certain time window) - messages can appear out of order due to this existing feature, along with simply messages moving faster than the bot.
I find the existing feature quite useful, but see a new opportunity for parity using the new edit feature.
