### ISSUE TITLE
Reply embeds do not respect server avatars

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [xSke/PluralKit#384]
Observe.

https://user-images.githubusercontent.com/14184826/128820723-6da9ba83-d384-4330-b6a7-7b04028190db.mp4

**Comment by vmorrisonwood** [comment]
I may be reading this wrong, but it looks like Server Avatars don't have an endpoint yet: [Link](https://discord.com/developers/docs/resources/user) 
The Reply Embed code just fetches the Avatar of the User replied to, and I guess in Discord's eyes that's the Default Avatar, not any Server Avatar that might be present:

https://github.com/xSke/PluralKit/blob/0b0ea5af1c4b8449f42676576b7c382ae0928929/PluralKit.Bot/Proxy/ProxyService.cs#L234

So this likely can't be fixed until Discord changes that behaviour or provides an endpoint. It seems like they're starting to roll it out again, so that may come sooner than later. Please correct me if I got anything wrong here!

**Comment by spiralw** [comment]
@vmorrisonwood you're looking for this PR: discord/discord-api-docs#3081
Discord API docs are often community-updated so sometimes updates get stuck at PR level for a while.

Either way, I'll push a fix in a few minutes.

**Comment by spiralw** [comment]
This should now be fixed.
