### ISSUE TITLE
Error when trying to set proxy tags that conflict with other members' tags

### ISSUE THREAD

**Issue by xSke** [xSke/PluralKit#84]
This is if both prefix and suffix match.
Don't know what it should do if there's a partial overlap (eg. `[text` and `[text]`).

**Comment by nyxthewitch** [comment]
I believe this is the issue we were having, if I understood correctly.
Previously, I was able to set the tag `;b` for one member and then `;bt` for another member with no conflict.
Now, I have tried to set `;n` as a tag for one member and `;nx` for another member. The `;nx` does not work and is interpreted as `;n`.

**Comment by PlatypodeCode** [comment]
I believe that the error would come from the order that pluralkit checks the proxy prefixes and suffixes.
So if `;bt`  member is checked before `;b` member, then there is no conflict, but if `;b` member is checked before `;bt` member, the bot will not check `;bt` because `;b` was already found. 
A potential solution could be to check the proxy of each member in length order (Longest proxy to shortest proxy).
This would mean that the longer proxies are checked first, so the shorter proxies that are the same as a start of a longer one, can only be checked if it's not a longer proxy

**Comment by xSke** [comment]
Yeah, that's a good idea. It's already sorting proxy matches by specificity (double-sided proxies are checked before single-sided proxies), this could be extended to sorting by the length of the prefix/suffix. I have a feeling there are some edge cases here re: how to order double-sided proxies (by length sum? max? min?) that I'd have to either reason my way through or just write a bunch of unit tests.

**Comment by xSke** [comment]
(whoops, didn't mean to close it)

**Comment by PlatypodeCode** [comment]
What if rather then having two separate checks for each end of the proxy, you turned each member's proxies into one regex query, and sorted by query string length? That way it will do the longest first no matter what. You also wouldn't need to seperate the proxies with just a prefix from those with both prefix and suffix, because that is also just a way of sorting them by length. It would also reduce the search code. If this string was stored in the member table with the member, it could also be accessed by API and used in other situations as a regex query.

**Comment by xSke** [comment]
Oh yeah - that's a good idea. It would be trivial to implement without regex, though. Might go with that instead.
